routes/admin.php
<?php
use  Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'middleware' => ['check.auth','check.is.admin']], function () {
    Route::get('/', function () {
        return view('layouts.app_admin');
    });

    Route::get('/dashboard','Admin\DashboardController@showView')->name('get_admin_dashboard');
    Route::resource('user', 'Admin\UserController');

   
  
    Route::get('lesson/part/question/list','Admin\LessonController@getListLessonPartQuestion')->name('lesson.part.question.list');

    Route::get('lesson/part/list','Admin\LessonPartController@getListLessonPart')->name('lesson.part.list');
    Route::post('lesson/part/question/random','Admin\LessonPartController@randomQuestion')->name('lesson.part.question.random');
    Route::resource('lesson-part', 'Admin\LessonPartController');
    
    Route::get('lesson/list','Admin\LessonController@getListLesson')->name('lesson.list');

    
    Route::resource('lesson', 'Admin\LessonController');
    Route::resource('topic', 'Admin\TopicController');
    Route::resource('practice', 'Admin\PracticeController');

    Route::get('vocabulary/list', 'Admin\VocabularyController@listVocabulary')->name('vocabulary.list');
    Route::resource('vocabulary', 'Admin\VocabularyController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('category', 'Admin\CategoryController');

    
    Route::post('test/random', 'Admin\TestController@randomGroupQuestion')->name('test.random');
    Route::resource('test', 'Admin\TestController');
    Route::resource('part', 'Admin\PartController');
    

    
    Route::get('question/list-l','Admin\QuestionController@getQuestionsAjaxLesson')->name('question.list.l');
    Route::get('question/list-p','Admin\QuestionController@getQuestionsAjaxPractice')->name('question.list.p');
    Route::get('question/list-sv','Admin\QuestionController@getQuestionsAjaxV2')->name('question.list.sv');
    Route::get('question/list','Admin\QuestionController@getQuestionsAjax')->name('question.list');
    Route::get('question/create-group','Admin\QuestionController@createGroup')->name('question.create.group');
    Route::post('question/create-raw','Admin\QuestionController@storeRawDataQuestionGroup')->name('question.create.raw');
    Route::get('question/edit-raw/{index}','Admin\QuestionController@showRawDataQuestionGroup')->name('question.edit.raw');
    Route::post('question/update-raw/{index}','Admin\QuestionController@updateRawDataQuestionGroup')->name('question.update.raw');
    Route::get('question/delete-raw/{index}','Admin\QuestionController@deleteRawQuestion')->name('question.delete.raw');
    
    Route::get('question-group/list','Admin\QuestionGroupController@showList')->name('question-group.list');
    Route::resource('question-group', 'Admin\QuestionGroupController');
    Route::resource('question', 'Admin\QuestionController');

    Route::put('setting/email','Admin\SettingController@changeEmailConfig')->name('setting.email');
    Route::put('setting/random','Admin\SettingController@changeRandomConfig')->name('setting.random');
    Route::put('setting/info','Admin\SettingController@changeInfoConfig')->name('setting.info');

    Route::resource('setting', 'Admin\SettingController');
    Route::get('file', function () {
        return view('admin.file.iframe');
    })->name('dashboard-file');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['check.auth','check.is.admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');


Route::get('xxx', function() {
    return view('admin.file.ckfinder');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('/dang-xuat', 'Auth\LoginController@logout')->name('put_logout');

Route::get('/dang-nhap', 'Auth\LoginController@showLogin')->name('get_login');

Route::post('/auth', 'Auth\LoginController@login')->name('post_login');

Route::get('/dang-ky', 'Auth\RegisterController@showView')->name('get_register');

Route::post('/user/register', 'Auth\RegisterController@register')->name('post_register');

Route::get('/quen-mat-khau', 'Auth\ForgotPasswordController@showView')->name('get_forgot');

Route::post('/post-forgot', 'Auth\ForgotPasswordController@requestForgotPassword')->name('post_forgot');

Route::get('/xac-thuc-email/{email}', 'Auth\VerificationController@verifyEmail')->name('put_verify');

Route::get('/khoi-phuc-mat-khau/{email}', 'Auth\ResetPasswordController@showView')->name('get_reset');

Route::post('/post-reset-password', 'Auth\ResetPasswordController@reset')->name('post_reset');

Route::group(['middleware' => ['check.auth', 'verified']], function () {

    Route::get('/dashboard', 'Member\DashboardController@index')->name('get_dashboard');

    //article
    Route::get('/bai-viet/{slug}', 'Member\ArticleController@detail')->name('article_detail');
    Route::get('/bai-viet', 'Member\ArticleController@list')->name('article_list');

    //part practice

    Route::get('/phan/{slug}/bai-tap', 'Member\PracticeController@list')->name('part_practices');

    Route::get('/bai-tap/{practice_slug}', 'Member\PracticeController@detail')->name('part_practices_detail');

    Route::post('/bai-tap/nop-bai', 'Member\PracticeController@create')->name('part_practices_create');

    //user
    Route::get('/ho-so', 'Member\ProfileController@profile')->name('user_profile');

    Route::put('/update-profile', 'Member\ProfileController@updateProfile')->name('update_profile');

    Route::put('/update-avatar', 'Member\ProfileController@uploadAvatar')->name('update_avatar');


    //lesson

    //topic
    Route::group(['prefix' => 'chu-de'], function () {
        Route::get('/', 'Member\TopicController@list')->name('topic_list');
        Route::get('/{slug}/tu-vung', 'Member\VocabularyController@index')->name('vocabulary_list');
    });

    Route::group(['prefix' => 'bai-giang'], function () {
        Route::get('/', 'Member\LessonController@list')->name('lesson_list');
        Route::get('{slug}/{part}', 'Member\LessonController@lessonPart')->name('lesson_part_detail');
        Route::get('{slug}', 'Member\LessonController@lesson')->name('lesson_detail');
    });
    Route::group(['prefix' => 'de-thi'], function () {
        
        Route::get('/lan-thi','Member\TestController@myTest')->name('my_test');
        Route::get('/','Member\TestController@list')->name('test_list');
        Route::get('/chi-tiet-dap-an/{id}','Member\TestController@getResult')->name('get-result');

        Route::get('/huong-dan/{id}','Member\TestController@preview')->name('get-preview');
        
        Route::get('thi/{id}','Member\TestController@detail')->name('test_detail');
        
        Route::post('/submit/{part}','Member\TestController@submit')->name('submit_test');
        
       

    });
});


Route::get('crawl-data', 'Crawl\CrawlController@showView');

Route::get('crawl/data', 'Crawl\CrawlController@showViewV2');


Route::post('run-crawl', 'Crawl\CrawlController@handle')->name('run');



Route::get('/init/test', function (){
    
    $questions = \App\Models\QuestionGroup::all();
    // $questions = \App\Models\QuestionGroup::where('question_group_id','>',45)->get();
    // $photoPath = 'easytoiec/public/storage/photos/shares/test/de1/audio';
    // return response()->json($questions );
    foreach($questions as $item) {
             
        if($item->question_group_image) {
            $item->question_group_image = 'https://toeic24.vn'. $item->question_group_image;
            $item->save();
        }
        // $test = new  App\Models\TestQuestion();
        // $test->test_id = 3;
        // $test->question_group_id =$item->question_group_id;
        // $test->save();
        }
    
    echo "done";

});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;
    //

    public $primaryKey = 'article_id';


    protected $fillable = [
        'article_avatar',
        'article_title',
        'article_slug',
        'article_content',
        'article_view_count',
        'article_category_id',
        'created_by',
        'article_publish'
    ];

    public function category()
    {
        return $this->hasOne(\App\Models\ArticleCategory::class, 'article_category_id', 'article_category_id');
    }
    public function author()
    {
        return $this->hasOne(\App\Models\User::class,'user_id','created_by');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ArticleCategory;
use App\Models\Article;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->keyword ?? null;
        $categoryId =  $request->category_id ?? null;
        $articleList  = Article::when($keyword, function ($query, $keyword) {
            return $query->where(
                'article_title',
                'like',
                "%$keyword%"
            )->orWhere(
                'article_content',
                'like',
                "%$keyword%"
            );
        })->when($categoryId, function ($query, $categoryId) {
            return $query->where('article_category_id', $categoryId);
        })->paginate(10);

        $categories = ArticleCategory::all();

        return view('admin.article.list')->with([
            'categories' => $categories,
            'articleList' => $articleList
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories = ArticleCategory::all();

        return view('admin.article.create')->with([
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try {
            $data = $request->except('_token');
            $data['article_slug'] = Str::slug($data['article_title']);
            $data['created_by'] = Auth::id();
            $data['article_view_count'] = 0;
            Article::create($data);
            $request->session()->flash('success', "Thêm bài viết thành công !");
            return redirect()->route('article.index');
        } catch (\Exception $e) {
            throw $e;
            $request->session()->flash('error', "Thêm bài viết thất bại !");
            return redirect()->route('article.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = ArticleCategory::all();
        $article = Article::findOrFail($id);
        return view('admin.article.edit')->with([
            'categories' => $categories,
            'article' => $article
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data = $request->except('_token', '_method');
            $data['article_slug'] = Str::slug($data['article_title']);
            $data['created_by'] = Auth::id();
            Article::where('article_id', $id)
                ->update($data);
            $request->session()->flash('success', "Cập nhật bài viết thành công !");
            return redirect()->route('article.index');
        } catch (\Exception $e) {
            throw $e;
            $request->session()->flash('error', "Cập nhật bài viết thất bại !");
            return redirect()->route('article.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            $ids = explode(',', $request->ids);
            Article::destroy($ids);
            $request->session()->flash('success', "Xoá bài viết thành công !");
            return redirect()->route('article.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', "Xoá bài viết thất bại !");
            return redirect()->route('article.index');
        }
    }
}






				

app/Http/Controllers/Member/ArticleController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\ArticleCategory;
class ArticleController extends Controller
{


    public function list(Request $request)
    {

        // $list = Article::paginate(10);

        $keyword = $request->keyword;
        $category = $request->category;

        $list =  Article::when($keyword, function ($query) use($keyword) {

            $query->where('article_title','LIKE','%'.$keyword.'%');

        })->when($category, function ($query) use($category) {

            $query->join('article_categories','article_categories.article_category_id','articles.article_category_id')
            ->where('articles.article_category_id',$category);

        })
        ->paginate(4);

        $listNew = Article::where('article_publish',1)->orderBy('created_at', 'desc')->limit(4)->get();
        $listHot =  Article::where('article_publish',1)->orderBy('article_view_count', 'desc')->limit(4)->get();
        $categories = ArticleCategory::all();
        return view('member.article.list',compact('list','categories','listNew','listHot'));
    }
    public function detail($slug)
    {   
      
        $article = Article::firstWhere(['article_slug'=>$slug,'article_publish'=>1]);
        if(!$article) abort(404);
        $listRandom = Article::inRandomOrder()->limit(4)->get();
        $article->increment('article_view_count',1);
        return view('member.article.detail',compact('article','listRandom'));
    }
}

resources/views/admin/article/list.blade.php
@extends('layouts.app_admin')
@section('head')
<title>Quản lý bài viết</title>
@endsection
@section('content')
<div class="d-flex">
    <nav id="breadcrumbs" class="mb-3">
        <ul>
            <li><a href="#"> <i class="uil-home-alt"></i> </a></li>
            <li><a href="#"> Bài viết </a></li>
            <li> Danh mục và Bài viết</li>
        </ul>
    </nav>
</div>
<div uk-grid="" class="uk-grid">
    <div class="uk-width-1-3@m uk-first-column">
        <nav class="responsive-tab style-3 setting-menu card uk-sticky" uk-sticky="top:30 ; offset:100; media:@m ;bottom:true; animation: uk-animation-slide-top" style="">
            <div class="card-header actions-toolbar border-0">
                <div class="d-flex justify-content-between align-items-center">
                    <h4 class="d-inline-block mb-0">Danh mục</h4>
                    <div class="d-flex">
                        <button onclick=" window.location.assign('{{route('category.create')}}')" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Thêm mới">
                            <i class="uil-file-plus text-success"></i>
                        </button>
                        <button class="btn btn-icon btn-hover  btn-circle btn-update" uk-tooltip="Cập nhật">
                            <i class="uil-pen text-warning"></i>
                        </button>

                        <button class="btn btn-icon btn-hover  btn-circle btn-delete" uk-tooltip="Xoá">
                            <i class="uil-trash-alt text-danger"></i>
                        </button>
                    </div>
                </div>
            </div>
            <hr class="m-0 uk-visible@m">
            <ul>
                <li id="all" >
                    <a href="{{ route('article.index')}}" class="text-center">
                       Tất cả
                    </a>
                </li>
                @foreach ($categories as $item)
                <li id="{{$item->article_category_id}}">
                    <a href="{{ route('article.index', ['category_id'=> $item->article_category_id]) }}">
                        <input  style="display: none"  value="{{$item->article_category_id}}" class="skin-square category-choice" type="checkbox">
                        {{ $item->article_category_name}}
                        <span class="badge badge-light ml-2 badge-sm">{{$item->articles->count()}}</span>
                    </a>
                </li>
                @endforeach

            </ul>
        </nav>
        <div class="uk-sticky-placeholder" style="height: 734px; margin: 0px 0px 20px;" hidden=""></div>

    </div>

    <div class="uk-width-2-3@m">

        <div class="card rounded">
            <!-- Card header -->
            <div class="card-header actions-toolbar border-0">
                <div class="d-flex justify-content-between align-items-center">
                    <h4 class="d-inline-block mb-0">Bài viết</h4>
                    <div class="d-flex">
                        <a href="#" class="btn btn-icon btn-hover  btn-circle" uk-tooltip="Tìm kiếm bài viết">
                            <i class="uil-search"></i>
                        </a>
                        <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                            <form class="uk-search uk-search-navbar uk-width-1-1" action="{{ route('article.index') }}">
                                <input class="uk-search-input shadow-0 uk-form-small" name="keyword" type="search" placeholder="Tìm kiếm" autofocus>
                            </form>
                        </div>
                        <a href="{{ route('article.create') }}" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Thêm mới">
                            <i class="uil-file-plus text-success"></i>
                        </a>
                        <button id="delete-article" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Xoá">
                            <i class="uil-trash-alt text-danger"></i>
                            <form id="form-article-delete" action="{{ route('article.destroy',0) }}" method="post" style="display:node">
                                @csrf
                                @method("delete")
                            </form>
                        </button>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center">
                    <thead>
                        <tr>
                            <th>
                                <input  style="display: none"  class="skin-square all" type="checkbox">
                            </th>
                            <th scope="col">Tiêu đề</th>
                            <th scope="col">Công khai</th>
                            {{-- <th scope="col">Ngày tạo</th> --}}
                            <th scope="col"> </th>
                        </tr>
                    </thead>
                    <tbody class="list">
                       
                        @foreach ($articleList as $item)
                        <tr>
                            <th scope="row">
                                <input  style="display: none"  value="{{ $item->article_id }}" class="skin-square check" type="checkbox">
                            </th>
                            <th scope="row">
                                <div class="media align-items-center">
                                    <div>
                                        <div class="avatar-parent-child" style="width: max-content">
                                            <img style="object-fit: cover;" src="{{ asset($item->article_avatar) }}" class="avatar rounded-circle">
                                        </div>
                                    </div>
                                    <div class="media-body ml-4">
                                        <a href="{{ route('article.edit', $item->article_id) }}" class="name h6 mb-0 text-sm">{{$item->article_title}}</a>
                                        <small class="d-block font-weight-bold">#{{$item->article_id}}</small>
                                    </div>
                                </div>
                            </th>
                            <td scope="row">
                            <span class="uk-label {{
                                $item->article_publish == 1 ? 'uk-label-success' : 'uk-label-error'
                                }} ">{{
                                $item->article_publish == 1 ? 'Công khai' : 'Ẩn'
                                }}</span>
                            </td>
                            {{-- <td>{{$item->created_at}}</td> --}}
                            <td class="text-right">
                                <!-- Actions -->
                                <div class="actions ml-3">
                                    {{-- <a href="{{ route('topic.show', $item->topic_id) }}" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Xem chi tiết">
                                        <i class="uil-external-link-alt text-info"></i> </a> --}}
                                    <a href="{{ route('article.edit', $item->article_id) }}" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Chỉnh sửa">
                                        <i class="uil-pen text-warning"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                       
                    </tbody>
                </table>
                @if ($articleList->isEmpty())
                <div class="empty-data">Không có dữ liệu</div>
                @else
                <div class="text-center" style="float:right; ">
                    {{ $articleList->links('vendor.pagination.default') }}
                </div>
                @endif
            </div>

        </div>

    </div>


</div>
@endsection

@section('js')
<script async src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
<script async src="{{ asset('assets/common/icheck-1.x/icheck.min.js') }}"></script>
<script async src="{{ asset('assets/admin/js/custom-icheck.js') }}"></script>
<script>
    $(function() {

       (function() {
            var url_string = window.location.href; 
           
            var url = new URL(url_string);
            var paramValue = url.searchParams.get("category_id");
           
            if(!paramValue) {
                $('#all').addClass('uk-active');
            } else {
                $('.uk-search').append(`<input name='category_id' type='hidden' value='${paramValue}' />`)
                $(`#${paramValue}`).addClass('uk-active');
            }
        })();
        $('.btn-update').on('click', function() {
            var check_parrent = $('.checked');
            var count_item = check_parrent.length;
            if (count_item === 0) {
                UIkit.modal.alert("Không có danh mục nào được chọn !", {
                    labels: {
                        ok: "Đóng"
                    }
                });
            } else {
                var id = $(check_parrent[0]).children('input').val();
                window.location.assign(`category/${id}/edit`);
            }
        });

        $('.btn-delete').on('click', function() {
            var check_parrent = $('.checked');
            var count_item = check_parrent.length;
            if (count_item === 0) {
                UIkit.modal.alert("Không có danh mục nào được chọn !", {
                    labels: {
                        ok: "Đóng"
                    }
                });
            } else {
                var ids = [];
                var from = $('#form-category-delete');
                $.each(check_parrent.children('input'), function(i, item) {
                    ids.push($(item).val());
                });
                ids = ids.join(',');
                from.attr('action', function(i, value) {
                    return `${value}?ids=${ids}`;
                });
                from.submit();
            }

        });
        $("#delete-article").on("click", function (e) {
        $check = $(".checked");
        if ($check.length === 0 ) {
            UIkit.modal.alert("Không có bài viết nào được chọn !", {
                    labels: {
                        ok: "Đóng"
                    }
                });
        }
        var ids = [];
        $.each($check, function (key, value) {
            var id = $(value).children("input").val();
            id != 'on' ?  ids.push( id  ) : '';
        });
        $("#form-article-delete").attr("action", function (index, value) {
            ids = ids.join(",");
            return `${value}?ids=${ids}`;
        });
        if(!ids.length) { return; }
        UIkit.modal
            .confirm("Bạn có chắc muốn xoá !", {
                labels: { ok: "Xoá", cancel: "Huỷ" },
            })
            .then(
                function () {
                    $("#form-article-delete").submit();
                },
                function (err) {}
            );
    });

    });

</script>
@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('assets/common/icheck-1.x/skins/all.css') }}">
<style>
    .empty-data {
        text-align: center;
        padding: 20px;
        padding-top: 0;
    }

    .image-preview {
        height: 282px;
        width: 100%;
        object-fit: cover;
        border: 1px solid #eceff5;
        border-radius: 7px;
        box-shadow: 0 0.010416667in 0.25pc 0in rgba(0, 0, 0, .12);

    }

    .color-purge {
        background-color: #3e416d !important
    }

    .wrapper-img {
        padding-top: 6px;
        padding-bottom: 4px;
        vertical-align: top;
        position: relative;
    }

</style>
@endsection