routes/admin.php
<?php
use  Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'middleware' => ['check.auth','check.is.admin']], function () {
    Route::get('/', function () {
        return view('layouts.app_admin');
    });

    Route::get('/dashboard','Admin\DashboardController@showView')->name('get_admin_dashboard');
    Route::resource('user', 'Admin\UserController');

   
  
    Route::get('lesson/part/question/list','Admin\LessonController@getListLessonPartQuestion')->name('lesson.part.question.list');

    Route::get('lesson/part/list','Admin\LessonPartController@getListLessonPart')->name('lesson.part.list');
    Route::post('lesson/part/question/random','Admin\LessonPartController@randomQuestion')->name('lesson.part.question.random');
    Route::resource('lesson-part', 'Admin\LessonPartController');
    
    Route::get('lesson/list','Admin\LessonController@getListLesson')->name('lesson.list');

    
    Route::resource('lesson', 'Admin\LessonController');
    Route::resource('topic', 'Admin\TopicController');
    Route::resource('practice', 'Admin\PracticeController');

    Route::get('vocabulary/list', 'Admin\VocabularyController@listVocabulary')->name('vocabulary.list');
    Route::resource('vocabulary', 'Admin\VocabularyController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('category', 'Admin\CategoryController');

    
    Route::post('test/random', 'Admin\TestController@randomGroupQuestion')->name('test.random');
    Route::resource('test', 'Admin\TestController');
    Route::resource('part', 'Admin\PartController');
    

    
    Route::get('question/list-l','Admin\QuestionController@getQuestionsAjaxLesson')->name('question.list.l');
    Route::get('question/list-p','Admin\QuestionController@getQuestionsAjaxPractice')->name('question.list.p');
    Route::get('question/list-sv','Admin\QuestionController@getQuestionsAjaxV2')->name('question.list.sv');
    Route::get('question/list','Admin\QuestionController@getQuestionsAjax')->name('question.list');
    Route::get('question/create-group','Admin\QuestionController@createGroup')->name('question.create.group');
    Route::post('question/create-raw','Admin\QuestionController@storeRawDataQuestionGroup')->name('question.create.raw');
    Route::get('question/edit-raw/{index}','Admin\QuestionController@showRawDataQuestionGroup')->name('question.edit.raw');
    Route::post('question/update-raw/{index}','Admin\QuestionController@updateRawDataQuestionGroup')->name('question.update.raw');
    Route::get('question/delete-raw/{index}','Admin\QuestionController@deleteRawQuestion')->name('question.delete.raw');
    
    Route::get('question-group/list','Admin\QuestionGroupController@showList')->name('question-group.list');
    Route::resource('question-group', 'Admin\QuestionGroupController');
    Route::resource('question', 'Admin\QuestionController');

    Route::put('setting/email','Admin\SettingController@changeEmailConfig')->name('setting.email');
    Route::put('setting/random','Admin\SettingController@changeRandomConfig')->name('setting.random');
    Route::put('setting/info','Admin\SettingController@changeInfoConfig')->name('setting.info');

    Route::resource('setting', 'Admin\SettingController');
    Route::get('file', function () {
        return view('admin.file.iframe');
    })->name('dashboard-file');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['check.auth','check.is.admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');


Route::get('xxx', function() {
    return view('admin.file.ckfinder');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('/dang-xuat', 'Auth\LoginController@logout')->name('put_logout');

Route::get('/dang-nhap', 'Auth\LoginController@showLogin')->name('get_login');

Route::post('/auth', 'Auth\LoginController@login')->name('post_login');

Route::get('/dang-ky', 'Auth\RegisterController@showView')->name('get_register');

Route::post('/user/register', 'Auth\RegisterController@register')->name('post_register');

Route::get('/quen-mat-khau', 'Auth\ForgotPasswordController@showView')->name('get_forgot');

Route::post('/post-forgot', 'Auth\ForgotPasswordController@requestForgotPassword')->name('post_forgot');

Route::get('/xac-thuc-email/{email}', 'Auth\VerificationController@verifyEmail')->name('put_verify');

Route::get('/khoi-phuc-mat-khau/{email}', 'Auth\ResetPasswordController@showView')->name('get_reset');

Route::post('/post-reset-password', 'Auth\ResetPasswordController@reset')->name('post_reset');

Route::group(['middleware' => ['check.auth', 'verified']], function () {

    Route::get('/dashboard', 'Member\DashboardController@index')->name('get_dashboard');

    //article
    Route::get('/bai-viet/{slug}', 'Member\ArticleController@detail')->name('article_detail');
    Route::get('/bai-viet', 'Member\ArticleController@list')->name('article_list');

    //part practice

    Route::get('/phan/{slug}/bai-tap', 'Member\PracticeController@list')->name('part_practices');

    Route::get('/bai-tap/{practice_slug}', 'Member\PracticeController@detail')->name('part_practices_detail');

    Route::post('/bai-tap/nop-bai', 'Member\PracticeController@create')->name('part_practices_create');

    //user
    Route::get('/ho-so', 'Member\ProfileController@profile')->name('user_profile');

    Route::put('/update-profile', 'Member\ProfileController@updateProfile')->name('update_profile');

    Route::put('/update-avatar', 'Member\ProfileController@uploadAvatar')->name('update_avatar');


    //lesson

    //topic
    Route::group(['prefix' => 'chu-de'], function () {
        Route::get('/', 'Member\TopicController@list')->name('topic_list');
        Route::get('/{slug}/tu-vung', 'Member\VocabularyController@index')->name('vocabulary_list');
    });

    Route::group(['prefix' => 'bai-giang'], function () {
        Route::get('/', 'Member\LessonController@list')->name('lesson_list');
        Route::get('{slug}/{part}', 'Member\LessonController@lessonPart')->name('lesson_part_detail');
        Route::get('{slug}', 'Member\LessonController@lesson')->name('lesson_detail');
    });
    Route::group(['prefix' => 'de-thi'], function () {
        
        Route::get('/lan-thi','Member\TestController@myTest')->name('my_test');
        Route::get('/','Member\TestController@list')->name('test_list');
        Route::get('/chi-tiet-dap-an/{id}','Member\TestController@getResult')->name('get-result');

        Route::get('/huong-dan/{id}','Member\TestController@preview')->name('get-preview');
        
        Route::get('thi/{id}','Member\TestController@detail')->name('test_detail');
        
        Route::post('/submit/{part}','Member\TestController@submit')->name('submit_test');
        
       

    });
});


Route::get('crawl-data', 'Crawl\CrawlController@showView');

Route::get('crawl/data', 'Crawl\CrawlController@showViewV2');


Route::post('run-crawl', 'Crawl\CrawlController@handle')->name('run');



Route::get('/init/test', function (){
    
    $questions = \App\Models\QuestionGroup::all();
    // $questions = \App\Models\QuestionGroup::where('question_group_id','>',45)->get();
    // $photoPath = 'easytoiec/public/storage/photos/shares/test/de1/audio';
    // return response()->json($questions );
    foreach($questions as $item) {
             
        if($item->question_group_image) {
            $item->question_group_image = 'https://toeic24.vn'. $item->question_group_image;
            $item->save();
        }
        // $test = new  App\Models\TestQuestion();
        // $test->test_id = 3;
        // $test->question_group_id =$item->question_group_id;
        // $test->save();
        }
    
    echo "done";

});

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Topic extends Model
{   
    use SoftDeletes;
    
    public $primaryKey = 'topic_id';


    protected $fillable = [
        'topic_name', 'topic_avatar', 'topic_slug', 'topic_description'
    ];

    public function vocabularies()
    {
        return $this->hasMany(\App\Models\Vocabulary::class,'topic_id','topic_id');
    }

}

app/Http/Controllers/Admin/TopicController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Topic;
use Illuminate\Support\Str;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\Topic\CreateTopicRequest;
use App\Http\Requests\Admin\Topic\UpdateTopicRequest;


class TopicController extends Controller
{
    private $topicList;
    private $showFormCreate;
    private $showFormView;

    public function __construct()
    {

        $this->topicList = collect(null);
        $this->showFormCreate = false;
        $this->showFormView = false;
        $this->disableInput = false;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->keyword;
        $this->topicList  =  Topic::when($keyword, function ($query) use($keyword) {

            $query->where('topic_name','LIKE','%'.$keyword.'%');

        })
        ->paginate(10);

        return view('admin.topic.list')->with(['topicList' => $this->topicList]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->showFormCreate = true;
        return  view('admin.topic.list')->with([
            'topicList' =>  $this->topicList,
            'showFormCreate' => $this->showFormCreate
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTopicRequest $request)
    {
        try {
            $data = $request->except('_token');
            $data['topic_slug'] = Str::slug($data['topic_name'], '-');
            Topic::create($data);
            $request->session()->flash('success', "Thêm mới thành công !");
            return redirect()->route('topic.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', "Thêm mới thất bại !");
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $topic = Topic::findOrFail($id);
            $this->showFormView = true;
            $this->disableInput = true;
            return  view('admin.topic.list')->with([
                'topicList' =>  $this->topicList,
                'showFormView' => $this->showFormView,
                'disableInput' => $this->disableInput,
                'topic' => $topic
            ]);
        } catch (\Exception $e) {
            // throw $e;
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        try {
            $topic = Topic::findOrFail($id);
            $this->showFormView = true;
            return  view('admin.topic.list')->with([
                'topicList' =>  $this->topicList,
                'showFormView' => $this->showFormView,
                'topic' => $topic
            ]);
        } catch (\Exception $e) {
            // throw $e;
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTopicRequest $request, $id)
    {
        try {
            $data = $request->except('_token', '_method');
            
            $data['topic_slug'] = Str::slug($data['topic_name'], '-');
            Topic::where('topic_id', $id)
                ->update($data);

            $request->session()->flash('success', "Cập nhật thành công !");
            return redirect()->route('topic.index');

        } catch (\Exception $e) {

            $request->session()->flash('error', "Cập nhật thất bại !");

            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            $flagNotDel = false;
            $msg = "";
            $ids = explode(',' , $request->ids);
            foreach ($ids as $k => $id) {
                // Topic::withCount('vocabularies')
                $topic = Topic::findOrFail($id);
                if($topic->vocabularies->count() >0) {
                    unset($ids[$k]);
                    $flagNotDel = true;
                }
            }
            Topic::destroy($ids);
            if($flagNotDel)
            $msg = ". Các topic chứa từ vựng sẽ không xóa được !";
            $request->session()->flash('success', "Xoá thành công".$msg);
            return redirect()->route('topic.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', "Xoá thất bại !");
            return redirect()->route('topic.index');
        }
    }
}

app/Http/Controllers/Member/TopicController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Topic;

class TopicController extends Controller
{
    public  function  list(Request $request) {

        $keyword = $request->keyword;

        $list =  Topic::when($keyword, function ($query) use($keyword) {

            $query->where('topic_name','LIKE','%'.$keyword.'%');

        })
        ->paginate(12);
        

        return view('member.topic.list', compact('list'));
    }

}

resources/views/admin/topic/create.blade.php
<div id="modal-topic-create" class="uk-modal-container" uk-modal bg-close="false">
    <div class="uk-modal-dialog">
        <div class="uk-modal-header">
            <h2 class="uk-modal-title">Tạo mới chủ đề</h2>
        </div>
        <div class="uk-modal-body">
            <form id="form-topic-create" class="uk-child-width-1-1 uk-grid-small uk-grid uk-grid-stack" method="post" action="{{ route('topic.store')}}">
                @csrf
                <div class="uk-width-1-2@m">

                    <div class="uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label">Ảnh đại diện</label>
                            <div class="uk-position-relative w-100" uk-form-custom>
                                <input type="hidden"  id="topic_avatar" name="topic_avatar">
                                <button data-path-name="path-name" data-preview="image-preview" data-input="topic_avatar" id="choice-photo" class="uk-button uk-button-default" type="button" tabindex="-1">
                                    <i class="uil-image-upload text-danger"></i>
                                    Chọn ảnh</button>
                                <span id="path-name"></span>
                                @error('topic_avatar')
                                <span class="text-right text-danger text-error" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="uk-grid-margin uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label">Xem trước ảnh đại diện</label>
                            <div class="uk-position-relative w-100">
                                <div class="wrapper-img" id="image-preview">
                                    <img class="image-preview" src="{{ asset('assets/nophoto.png') }}">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="uk-width-1-2@m">
                    <div class="uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label"> Tên chủ để</label>
                            <div class="uk-position-relative w-100">
                                <input class="uk-input" type="text" name="topic_name"  placeholder="Tối đa 100 ký tự">
                                @error('topic_name')
                                <span class="text-right text-danger text-error" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="uk-grid-margin uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label">Mô tả ngắn</label>
                            <div class="uk-position-relative w-100">
                                <textarea class="uk-textarea" rows="10" name="topic_description" placeholder="Tối đa 255 ký tự"></textarea>
                                @error('topic_description')
                                <span class="text-right text-danger text-error" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
        <div class="uk-modal-footer uk-text-right">
            <div class="uk-flex uk-flex-right p-4">
                <button onclick=" window.location.assign('{{route('topic.index')}}')" type="button" class="btn  btn-light mr-2">Hủy</button>
                <button class="btn btn-default"  onclick="document.getElementById('form-topic-create').submit()" >Lưu</button>
            </div>

        </div>
    </div>
</div>

resources/views/admin/topic/edit.blade.php
<div id="modal-topic-show-edit" class="uk-modal-container" uk-modal bg-close="false">
    <div class="uk-modal-dialog"> <button class="uk-modal-close-default" type="button" uk-close></button>
        <div class="uk-modal-header">
            <h2 class="uk-modal-title"> {{ isset($disableInput) ? "Chi tiết chủ đề": "Chỉnh sửa chủ đề" }} </h2>
        </div>
        <div class="uk-modal-body">
            <form id="form-update-topic" class="uk-child-width-1-1 uk-grid-small uk-grid uk-grid-stack" method="post" action="{{ route('topic.update',$topic->topic_id)}}" enctype="multipart/form-data">
                @csrf
                @method("put")
                <div class="uk-width-1-2@m">

                    @if(!isset($disableInput))
                    <div class="uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label">Ảnh đại diện</label>
                            <div class="uk-position-relative w-100" uk-form-custom>
                                <input value="{{$topic->topic_avatar}}" type="hidden"  id="topic_avatar" name="topic_avatar">
                                <button  id="choice-photo" data-path-name="path-name" data-preview="image-preview" data-input="topic_avatar" class="uk-button uk-button-default" type="button">
                                    <i class="uil-image-upload text-danger"></i>
                                    Chọn ảnh</button>
                                <span id="path-name">{{$topic->topic_avatar}}</span>
                            </div>
                        </div>
                    </div>
                    @endif
                    <div class="uk-grid-margin uk-first-column">
                        <div class="uk-form-group">
                        <label class="uk-form-label">{{ isset($disableInput) ? "Ảnh đại diện" : "Xem trước ảnh đại diện" }}</label>
                            <div class="uk-position-relative w-100">
                                <div class="wrapper-img" id="image-preview">
                                    <img class="image-preview" src="{{ asset($topic->topic_avatar) }}" style='{{ isset($disableInput) ? "height: 380px;" : "" }}' >
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="uk-width-1-2@m">
                    <div class="uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label"> Tên chủ để</label>
                            <div class="uk-position-relative w-100">
                                <input value="{{$topic->topic_name}}" class="uk-input" type="text" name="topic_name" {{ isset($disableInput) ? "disabled" : "" }}>
                                @error('topic_name')
                                <span class="text-right text-danger text-error" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="uk-grid-margin uk-first-column">
                        <div class="uk-form-group">
                            <label class="uk-form-label">Mô tả ngắn</label>
                            <div class="uk-position-relative w-100">
                            <textarea class="uk-textarea" rows="10" name="topic_description" {{ isset($disableInput) ? "disabled" : "" }}>{{$topic->topic_description}}</textarea>
                            @error('topic_description')
                            <span class="text-right text-danger text-error" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
        <div class="uk-modal-footer uk-text-right">
            <div class="uk-flex uk-flex-right p-4">

            @if (isset($disableInput) )
                <button onclick=" window.location.assign('{{route('topic.index')}}')" type="button" class="btn  btn-light mr-2">Hủy</button>
                <button class="btn btn-default"   onclick=" window.location.assign('{{route('topic.edit',$topic->topic_id)}}')" >Sửa</button>

            @else
                <button onclick=" window.location.assign('{{route('topic.index')}}')" type="button" class="btn  btn-light mr-2">Hủy</button>
                <button class="btn btn-default"  onclick="document.getElementById('form-update-topic').submit()" >Lưu</button>
            @endif


            </div>
        </div>
    </div>
</div>

resources/views/admin/topic/list.blade.php
@extends('layouts.app_admin')
@section('head')
<title>Quản lý chủ đề</title>
@endsection
@section('content')
<div class="d-flex">
    <nav id="breadcrumbs" class="mb-3">
        <ul>
            <li><a href="#"> <i class="uil-home-alt"></i> </a></li>
            <li><a href="#"> Chủ đề </a></li>
            <li>Danh sách</li>
        </ul>
    </nav>
</div>
<div class="card">
    <!-- Card header -->
    <div class="card-header actions-toolbar border-0">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="d-inline-block mb-0">Chủ đề</h4>
            <div class="d-flex">

                <a href="#" class="btn btn-icon btn-hover  btn-circle" uk-tooltip="Tìm kiếm">
                    <i class="uil-search"></i>
                </a>
                <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                    <form class="uk-search uk-search-navbar uk-width-1-1" method="get" action="{{ route('topic.index') }}">
                        <input name="keyword" class="uk-search-input shadow-0 uk-form-small" type="search" placeholder="Tìm kiếm"
                            autofocus>
                    </form>
                </div>
                <a  href="{{ route('topic.create') }}" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Thêm mới">
                    <i class="uil-file-plus text-success"></i>
                </a>
                <button  id="delete-topic" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Xoá">
                    <i class="uil-trash-alt text-danger"></i>
                    <form method="POST" style="display:node" id="form-delete-topic" action="{{ route('topic.destroy',0)}}">
                        @method("delete")
                        @csrf
                    </form>
                </button>
            </div>
        </div>
    </div>
    <!-- Table -->
    <div class="table-responsive">
        <table class="table align-items-center">
            <thead>
                <tr>
                    <th>
                        <input  style="display: none"  class="skin-square all" type="checkbox">
                    </th>
                    <th scope="col">Tên chủ đề</th>
                    <th scope="col">Số từ vựng</th>
                    <th scope="col">Ngày tạo</th>
                    <th scope="col"> </th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($topicList as $item)
                <tr>
                    <th scope="row">
                        <input style="display: none" value="{{ $item->topic_id }}" class="skin-square check" type="checkbox">
                    </th>
                    <th scope="row">
                        <div class="media align-items-center">
                            <div>
                                <div class="avatar-parent-child" style="width: max-content">
                                    <img alt="Image placeholder" src="{{ asset($item->topic_avatar) }}" class="avatar rounded-circle">
                                </div>
                            </div>
                            <div class="media-body ml-4">
                                <a href="{{ route('topic.show', $item->topic_id) }}" class="name h6 mb-0 text-sm">{{$item->topic_name}}</a>
                                <small class="d-block font-weight-bold">#{{$item->topic_id}}</small>
                            </div>
                        </div>
                    </th>
                    <td scope="row">
                        <span class="uk-label uk-label-success">{{ $item->vocabularies->count()}}</span>
                    </td>
                    <td>{{$item->created_at}}</td>
                    <td class="text-right">
                        <!-- Actions -->
                        <div class="actions ml-3">
                            <a href="{{ route('topic.show', $item->topic_id) }}" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Xem chi tiết">
                                <i class="uil-external-link-alt text-info"></i> </a>
                            <a href="{{ route('topic.edit', $item->topic_id) }}" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Chỉnh sửa">
                                <i class="uil-pen text-warning"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @if ($topicList->isEmpty())
        <div class="empty-data">Không có dữ liệu</div>
        @else
        <div class="text-center" style="float:right; ">
            {{ $topicList->links('vendor.pagination.default') }}
        </div>
        @endif
    </div>
</div>

@endsection
@section('js')
<script   src="{{ asset('assets/admin/js/topic/list.js') }}"></script>
<script  src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
@if(isset($showFormCreate))
@include('admin.topic.create')
<script  src="{{ asset('assets/admin/js/topic/create.js') }}"></script>
@endif
@if(isset($showFormView))
@include('admin.topic.edit')
<script  src="{{ asset('assets/admin/js/topic/edit.js') }}"></script>
@endif
@if(!isset($showFormCreate) && !isset($showFormView) )
<script  src="{{ asset('assets/common/icheck-1.x/icheck.min.js') }}"></script>
<script   src="{{ asset('assets/admin/js/custom-icheck.js') }}"></script>
@endif
@endsection

@section('css')
@if(!isset($showFormCreate) && !isset($showFormView) )
<link rel="stylesheet" href="{{ asset('assets/common/icheck-1.x/skins/all.css') }}">
@endif
@endsection