routes/admin.php
<?php
use  Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'middleware' => ['check.auth','check.is.admin']], function () {
    Route::get('/', function () {
        return view('layouts.app_admin');
    });

    Route::get('/dashboard','Admin\DashboardController@showView')->name('get_admin_dashboard');
    Route::resource('user', 'Admin\UserController');

   
  
    Route::get('lesson/part/question/list','Admin\LessonController@getListLessonPartQuestion')->name('lesson.part.question.list');

    Route::get('lesson/part/list','Admin\LessonPartController@getListLessonPart')->name('lesson.part.list');
    Route::post('lesson/part/question/random','Admin\LessonPartController@randomQuestion')->name('lesson.part.question.random');
    Route::resource('lesson-part', 'Admin\LessonPartController');
    
    Route::get('lesson/list','Admin\LessonController@getListLesson')->name('lesson.list');

    
    Route::resource('lesson', 'Admin\LessonController');
    Route::resource('topic', 'Admin\TopicController');
    Route::resource('practice', 'Admin\PracticeController');

    Route::get('vocabulary/list', 'Admin\VocabularyController@listVocabulary')->name('vocabulary.list');
    Route::resource('vocabulary', 'Admin\VocabularyController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('category', 'Admin\CategoryController');

    
    Route::post('test/random', 'Admin\TestController@randomGroupQuestion')->name('test.random');
    Route::resource('test', 'Admin\TestController');
    Route::resource('part', 'Admin\PartController');
    

    
    Route::get('question/list-l','Admin\QuestionController@getQuestionsAjaxLesson')->name('question.list.l');
    Route::get('question/list-p','Admin\QuestionController@getQuestionsAjaxPractice')->name('question.list.p');
    Route::get('question/list-sv','Admin\QuestionController@getQuestionsAjaxV2')->name('question.list.sv');
    Route::get('question/list','Admin\QuestionController@getQuestionsAjax')->name('question.list');
    Route::get('question/create-group','Admin\QuestionController@createGroup')->name('question.create.group');
    Route::post('question/create-raw','Admin\QuestionController@storeRawDataQuestionGroup')->name('question.create.raw');
    Route::get('question/edit-raw/{index}','Admin\QuestionController@showRawDataQuestionGroup')->name('question.edit.raw');
    Route::post('question/update-raw/{index}','Admin\QuestionController@updateRawDataQuestionGroup')->name('question.update.raw');
    Route::get('question/delete-raw/{index}','Admin\QuestionController@deleteRawQuestion')->name('question.delete.raw');
    
    Route::get('question-group/list','Admin\QuestionGroupController@showList')->name('question-group.list');
    Route::resource('question-group', 'Admin\QuestionGroupController');
    Route::resource('question', 'Admin\QuestionController');

    Route::put('setting/email','Admin\SettingController@changeEmailConfig')->name('setting.email');
    Route::put('setting/random','Admin\SettingController@changeRandomConfig')->name('setting.random');
    Route::put('setting/info','Admin\SettingController@changeInfoConfig')->name('setting.info');

    Route::resource('setting', 'Admin\SettingController');
    Route::get('file', function () {
        return view('admin.file.iframe');
    })->name('dashboard-file');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['check.auth','check.is.admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');


Route::get('xxx', function() {
    return view('admin.file.ckfinder');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('/dang-xuat', 'Auth\LoginController@logout')->name('put_logout');

Route::get('/dang-nhap', 'Auth\LoginController@showLogin')->name('get_login');

Route::post('/auth', 'Auth\LoginController@login')->name('post_login');

Route::get('/dang-ky', 'Auth\RegisterController@showView')->name('get_register');

Route::post('/user/register', 'Auth\RegisterController@register')->name('post_register');

Route::get('/quen-mat-khau', 'Auth\ForgotPasswordController@showView')->name('get_forgot');

Route::post('/post-forgot', 'Auth\ForgotPasswordController@requestForgotPassword')->name('post_forgot');

Route::get('/xac-thuc-email/{email}', 'Auth\VerificationController@verifyEmail')->name('put_verify');

Route::get('/khoi-phuc-mat-khau/{email}', 'Auth\ResetPasswordController@showView')->name('get_reset');

Route::post('/post-reset-password', 'Auth\ResetPasswordController@reset')->name('post_reset');

Route::group(['middleware' => ['check.auth', 'verified']], function () {

    Route::get('/dashboard', 'Member\DashboardController@index')->name('get_dashboard');

    //article
    Route::get('/bai-viet/{slug}', 'Member\ArticleController@detail')->name('article_detail');
    Route::get('/bai-viet', 'Member\ArticleController@list')->name('article_list');

    //part practice

    Route::get('/phan/{slug}/bai-tap', 'Member\PracticeController@list')->name('part_practices');

    Route::get('/bai-tap/{practice_slug}', 'Member\PracticeController@detail')->name('part_practices_detail');

    Route::post('/bai-tap/nop-bai', 'Member\PracticeController@create')->name('part_practices_create');

    //user
    Route::get('/ho-so', 'Member\ProfileController@profile')->name('user_profile');

    Route::put('/update-profile', 'Member\ProfileController@updateProfile')->name('update_profile');

    Route::put('/update-avatar', 'Member\ProfileController@uploadAvatar')->name('update_avatar');


    //lesson

    //topic
    Route::group(['prefix' => 'chu-de'], function () {
        Route::get('/', 'Member\TopicController@list')->name('topic_list');
        Route::get('/{slug}/tu-vung', 'Member\VocabularyController@index')->name('vocabulary_list');
    });

    Route::group(['prefix' => 'bai-giang'], function () {
        Route::get('/', 'Member\LessonController@list')->name('lesson_list');
        Route::get('{slug}/{part}', 'Member\LessonController@lessonPart')->name('lesson_part_detail');
        Route::get('{slug}', 'Member\LessonController@lesson')->name('lesson_detail');
    });
    Route::group(['prefix' => 'de-thi'], function () {
        
        Route::get('/lan-thi','Member\TestController@myTest')->name('my_test');
        Route::get('/','Member\TestController@list')->name('test_list');
        Route::get('/chi-tiet-dap-an/{id}','Member\TestController@getResult')->name('get-result');

        Route::get('/huong-dan/{id}','Member\TestController@preview')->name('get-preview');
        
        Route::get('thi/{id}','Member\TestController@detail')->name('test_detail');
        
        Route::post('/submit/{part}','Member\TestController@submit')->name('submit_test');
        
       

    });
});


Route::get('crawl-data', 'Crawl\CrawlController@showView');

Route::get('crawl/data', 'Crawl\CrawlController@showViewV2');


Route::post('run-crawl', 'Crawl\CrawlController@handle')->name('run');



Route::get('/init/test', function (){
    
    $questions = \App\Models\QuestionGroup::all();
    // $questions = \App\Models\QuestionGroup::where('question_group_id','>',45)->get();
    // $photoPath = 'easytoiec/public/storage/photos/shares/test/de1/audio';
    // return response()->json($questions );
    foreach($questions as $item) {
             
        if($item->question_group_image) {
            $item->question_group_image = 'https://toeic24.vn'. $item->question_group_image;
            $item->save();
        }
        // $test = new  App\Models\TestQuestion();
        // $test->test_id = 3;
        // $test->question_group_id =$item->question_group_id;
        // $test->save();
        }
    
    echo "done";

});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    // use SoftDeletes;
    
    public $primaryKey = 'question_id';
    
    protected $appends = ['action','check'];

    protected $fillable = [
        'question', 'question_scores', 'question_audio', 'question_image','part_id','question_time','question_group_id'
    ];

    public function questionGroup()
    {
        return $this->hasOne(\App\Models\QuestionGroup::class,'question_group_id','question_group_id');
    }

    public function answers() {
        return $this->hasMany(\App\Models\Answer::class,'question_id','question_id');
    }

    public function practice()
    {
        return $this->hasOne(\App\Models\Practice::class,'practice_questions', 'practice_id', 'question_id');
    }

    public function part() {
        return $this->hasOne(\App\Models\Part::class,'part_id','part_id');
    }

    protected $casts = [
        'question_time' => 'integer'
    ];

    public function getActionAttribute()
    {
        return '<a href="' . route('question.edit', $this->question_id) . '" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Chỉnh sửa" title="" aria-expanded="false">
                    <i class="uil-pen text-warning"></i>
               </a>';
    }

    public function getCheckAttribute()
    {
        return '<input class="skin-square check" type="checkbox" value="'.$this->question_id.'">';
    }
}

resources/views/admin/question/tab/create.blade.php
<div id="sigle-input">
    <div class="uk-first-column">
        <h5 class="uk-text-bold mb-2">Tên câu hỏi</h5>
        <input name="question" type="text" class="uk-input" placeholder="Tối đa 100 ký tự">
    </div>
    <div class="uk-first-column">
        <h5 class="uk-text-bold mb-2">Số điểm</h5>
        <input name="question_scores" type="number" class="uk-input">
    </div>
    <div uk-gird class="uk-grid">
        <div class="uk-width-1-2@m uk-first-column">
            <div class="uk-first-column">
                <h5 class="uk-text-bold mb-2">Ảnh mô tả </h5>
                <input type="hidden" id="question_image" name="question_image">
                <button data-path-name="path-name-photo" data-preview="image-preview" data-input="question_image"
                    id="question-image" class="uk-button uk-button-default" type="button" tabindex="-1">
                    <i class="uil-image-upload text-danger"></i>
                    Chọn ảnh</button>
                <span id="path-name-photo"></span>
            </div>
            <div class="uk-first-column">
                <div class="wrapper-img" id="image-preview">
                    <img class="image-preview" src="{{ asset('assets/nophoto.png') }}">
                </div>
            </div>

        </div>
        <div class="uk-width-1-2@m uk-first-column">
            <div class="uk-first-column">
                <h5 class="uk-text-bold mb-2">Âm thanh mô tả </h5>
                <input type="hidden" id="question_audio" name="question_audio">
                <button data-path-name="path-name-audio" data-audio="audio-preview" data-input="question_audio"
                    id="question-audio" class="uk-button uk-button-default" type="button" tabindex="-1">
                    <i class="uil-file-upload text-danger"></i>
                    Chọn âm</button>
                <span id="path-name-audio"></span>
            </div>
            <div class="uk-first-column">
                <div class="wrapper-img">
                    <div class="image-preview" style="text-align: center">
                        <audio controls class="audio-preview">
                            <source src="#">
                        </audio>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="uk-first-column">
        <h5 class="uk-text-bold mb-2">Đáp án</h5>
        <div id="no-answer" style="color:#f0506e ">
            <i  class="error help-block">Vui lòng thêm câu trả lời !</i>
        </div>
        <button id="btn-add-question" type="button" class="btn btn-animated btn-success btn-animated-x ">
            <span class="btn-inner--visible">Thêm đáp án</span>
            <span class="btn-inner--hidden">
                <i class="uil-plus"></i>
            </span>
        </button>

        <div id="question-container" uk-sortable="group:sortable-group">

        </div>
    </div>
    <div class="uk-flex uk-flex-right p-4">
        <button onclick="window.location.assign(' {{ route('question.index') }} ')"
            class="btn btn-outline-danger uk-first-column mr-2">
            Huỷ
        </button>

        <button class="btn btn-outline-success btn-create-single-question" type="submit">
            Tạo mới</button>
    </div>
</div>

resources/views/admin/question/tab/edit.blade.php
<div id="sigle-input">
    <div class="uk-first-column">
        @if ( isset($group_id) )
        <input type="hidden" name="question_group_id" value="{{$group_id}}" />
        <input type="hidden" name="callback" value="{{$callback}}" />
        
        @endif
        <h5 class="uk-text-bold mb-2">Tên câu hỏi</h5>
        <input value="{{$question->question}}" name="question" type="text" class="uk-input" placeholder="Tối đa 200 ký tự">
    </div>
    <div class="uk-first-column">
        <h5 class="uk-text-bold mb-2">Số điểm</h5>
        <input value="{{$question->question_scores}}" name="question_scores" type="number" class="uk-input">
    </div>
    <div uk-gird class="uk-grid">
        <div class="uk-width-1-2@m uk-first-column">
            <div class="uk-first-column">
                <h5 class="uk-text-bold mb-2">Ảnh mô tả </h5>
                <input type="hidden" id="question_image" name="question_image" value="{{$question->question_image}}">
                <button data-path-name="path-name-photo" data-preview="image-preview" data-input="question_image" id="question-image" class="uk-button uk-button-default" type="button" tabindex="-1">
                    <i class="uil-image-upload text-danger"></i>
                    Chọn ảnh</button>
                <span id="path-name-photo">{{$question->question_image}}</span>

            </div>
            <div class="uk-first-column">
                <div class="wrapper-img" id="image-preview">
                    <img class="image-preview" src="{{ $question->question_image ?
                    asset($question->question_image) :
                    asset('assets/nophoto.png') }}">
                </div>
            </div>

        </div>
        <div class="uk-width-1-2@m uk-first-column">
            <div class="uk-first-column">
                <h5 class="uk-text-bold mb-2">Âm thanh mô tả </h5>
                <input type="hidden" id="question_audio" name="question_audio" value="{{$question->question_audio}}">
                <button data-path-name="path-name-audio" data-audio="audio-preview" data-input="question_audio" id="question-audio" class="uk-button uk-button-default" type="button" tabindex="-1">
                    <i class="uil-file-upload text-danger"></i>
                    Chọn âm</button>
                <span id="path-name-audio">{{$question->question_audio}}</span>
            </div>
            <div class="uk-first-column">
                <div class="wrapper-img">
                    <div class="image-preview" style="text-align: center">
                        <audio controls class="audio-preview">
                            <source src="{{ $question->question_audio ?
                                asset($question->question_audio) :
                                '#' }}">
                        </audio>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="uk-first-column">
        <h5 class="uk-text-bold mb-2">Đáp án</h5>
        <div id="no-answer" style="color:#f0506e ">
            <i class="error help-block">Vui lòng thêm câu trả lời !</i>
        </div>
        <button id="btn-add-question" type="button" class="btn btn-animated btn-success btn-animated-x ">
            <span class="btn-inner--visible">Thêm đáp án</span>
            <span class="btn-inner--hidden">
                <i class="uil-plus"></i>
            </span>
        </button>

        <div id="question-container" uk-sortable="group:sortable-group">
            @foreach ($question->answers as $item)
            <input type="hidden" name="answer_id[]" value="{{$item->answer_id}}">
            <div class="uk-margin wrapper-question">
                <div class="uk-card uk-card-default uk-card-body uk-card-small">
                   <input value="{{$item->answer_option}}" name="answer_option[]" type="text" class="uk-input uk-grid-small answer-option"  placeholder="Nhập đáp án">
                    <div class="wp" style="float:right">
                        <input {{ $item->answer_is_correct ? 'checked' : '' }} value="{{$item->answer_option}}" class="skin-square is-corect" type="radio" name="is_corect"> Đáp án đúng
                        <button type="button" class="btn btn-icon btn-hover btn-circle btn-delete-question" uk-tooltip="Xóa" title="" aria-expanded="false">
                            <i class="uil-trash-alt text-danger"></i>
                        </button>
                    </div>
                </div>
            </div> 
            @endforeach
        </div>
    </div>
    <div class="uk-flex uk-flex-right p-4">
        <button onclick="window.location.assign(' {{ route('question.index') }} ')" class="btn btn-outline-danger uk-first-column mr-2">
            Huỷ
        </button>

        <button class="btn btn-outline-success btn-create-single-question" type="submit">
            Cập nhật</button>
    </div>
</div>

resources/views/admin/question/tab/upload.blade.php
<div class=" uk-child-width-2-3@m uk-grid-small p-4 uk-grid" uk-grid="">

    <div class="uk-first-column  js-upload" uk-form-custom>
        <h5 class="uk-text-bold mb-2">Tải lên file excel hoặc csv</h5>
     
        <button  id="choice-file" class="uk-button uk-button-default" type="button" tabindex="-1">
            <i class="uil-file-upload text-danger"></i>
            <span id="uploading"> Chọn file</span>
            <input type="file" id="upload_file" name="upload_file">
            <span id="progress-value"></span>
        </button>
        <span id="path-name"></span>
    
            <progress   id="js-progressbar" class="uk-progress" value="10" max="100">
            
            </progress>
      
        @error('topic_avatar')
        <span class="text-right text-danger text-error" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
        
    </div>
    
</div>