routes/admin.php
<?php
use  Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'middleware' => ['check.auth','check.is.admin']], function () {
    Route::get('/', function () {
        return view('layouts.app_admin');
    });

    Route::get('/dashboard','Admin\DashboardController@showView')->name('get_admin_dashboard');
    Route::resource('user', 'Admin\UserController');

   
  
    Route::get('lesson/part/question/list','Admin\LessonController@getListLessonPartQuestion')->name('lesson.part.question.list');

    Route::get('lesson/part/list','Admin\LessonPartController@getListLessonPart')->name('lesson.part.list');
    Route::post('lesson/part/question/random','Admin\LessonPartController@randomQuestion')->name('lesson.part.question.random');
    Route::resource('lesson-part', 'Admin\LessonPartController');
    
    Route::get('lesson/list','Admin\LessonController@getListLesson')->name('lesson.list');

    
    Route::resource('lesson', 'Admin\LessonController');
    Route::resource('topic', 'Admin\TopicController');
    Route::resource('practice', 'Admin\PracticeController');

    Route::get('vocabulary/list', 'Admin\VocabularyController@listVocabulary')->name('vocabulary.list');
    Route::resource('vocabulary', 'Admin\VocabularyController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('category', 'Admin\CategoryController');

    
    Route::post('test/random', 'Admin\TestController@randomGroupQuestion')->name('test.random');
    Route::resource('test', 'Admin\TestController');
    Route::resource('part', 'Admin\PartController');
    

    
    Route::get('question/list-l','Admin\QuestionController@getQuestionsAjaxLesson')->name('question.list.l');
    Route::get('question/list-p','Admin\QuestionController@getQuestionsAjaxPractice')->name('question.list.p');
    Route::get('question/list-sv','Admin\QuestionController@getQuestionsAjaxV2')->name('question.list.sv');
    Route::get('question/list','Admin\QuestionController@getQuestionsAjax')->name('question.list');
    Route::get('question/create-group','Admin\QuestionController@createGroup')->name('question.create.group');
    Route::post('question/create-raw','Admin\QuestionController@storeRawDataQuestionGroup')->name('question.create.raw');
    Route::get('question/edit-raw/{index}','Admin\QuestionController@showRawDataQuestionGroup')->name('question.edit.raw');
    Route::post('question/update-raw/{index}','Admin\QuestionController@updateRawDataQuestionGroup')->name('question.update.raw');
    Route::get('question/delete-raw/{index}','Admin\QuestionController@deleteRawQuestion')->name('question.delete.raw');
    
    Route::get('question-group/list','Admin\QuestionGroupController@showList')->name('question-group.list');
    Route::resource('question-group', 'Admin\QuestionGroupController');
    Route::resource('question', 'Admin\QuestionController');

    Route::put('setting/email','Admin\SettingController@changeEmailConfig')->name('setting.email');
    Route::put('setting/random','Admin\SettingController@changeRandomConfig')->name('setting.random');
    Route::put('setting/info','Admin\SettingController@changeInfoConfig')->name('setting.info');

    Route::resource('setting', 'Admin\SettingController');
    Route::get('file', function () {
        return view('admin.file.iframe');
    })->name('dashboard-file');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['check.auth','check.is.admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');


Route::get('xxx', function() {
    return view('admin.file.ckfinder');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('/dang-xuat', 'Auth\LoginController@logout')->name('put_logout');

Route::get('/dang-nhap', 'Auth\LoginController@showLogin')->name('get_login');

Route::post('/auth', 'Auth\LoginController@login')->name('post_login');

Route::get('/dang-ky', 'Auth\RegisterController@showView')->name('get_register');

Route::post('/user/register', 'Auth\RegisterController@register')->name('post_register');

Route::get('/quen-mat-khau', 'Auth\ForgotPasswordController@showView')->name('get_forgot');

Route::post('/post-forgot', 'Auth\ForgotPasswordController@requestForgotPassword')->name('post_forgot');

Route::get('/xac-thuc-email/{email}', 'Auth\VerificationController@verifyEmail')->name('put_verify');

Route::get('/khoi-phuc-mat-khau/{email}', 'Auth\ResetPasswordController@showView')->name('get_reset');

Route::post('/post-reset-password', 'Auth\ResetPasswordController@reset')->name('post_reset');

Route::group(['middleware' => ['check.auth', 'verified']], function () {

    Route::get('/dashboard', 'Member\DashboardController@index')->name('get_dashboard');

    //article
    Route::get('/bai-viet/{slug}', 'Member\ArticleController@detail')->name('article_detail');
    Route::get('/bai-viet', 'Member\ArticleController@list')->name('article_list');

    //part practice

    Route::get('/phan/{slug}/bai-tap', 'Member\PracticeController@list')->name('part_practices');

    Route::get('/bai-tap/{practice_slug}', 'Member\PracticeController@detail')->name('part_practices_detail');

    Route::post('/bai-tap/nop-bai', 'Member\PracticeController@create')->name('part_practices_create');

    //user
    Route::get('/ho-so', 'Member\ProfileController@profile')->name('user_profile');

    Route::put('/update-profile', 'Member\ProfileController@updateProfile')->name('update_profile');

    Route::put('/update-avatar', 'Member\ProfileController@uploadAvatar')->name('update_avatar');


    //lesson

    //topic
    Route::group(['prefix' => 'chu-de'], function () {
        Route::get('/', 'Member\TopicController@list')->name('topic_list');
        Route::get('/{slug}/tu-vung', 'Member\VocabularyController@index')->name('vocabulary_list');
    });

    Route::group(['prefix' => 'bai-giang'], function () {
        Route::get('/', 'Member\LessonController@list')->name('lesson_list');
        Route::get('{slug}/{part}', 'Member\LessonController@lessonPart')->name('lesson_part_detail');
        Route::get('{slug}', 'Member\LessonController@lesson')->name('lesson_detail');
    });
    Route::group(['prefix' => 'de-thi'], function () {
        
        Route::get('/lan-thi','Member\TestController@myTest')->name('my_test');
        Route::get('/','Member\TestController@list')->name('test_list');
        Route::get('/chi-tiet-dap-an/{id}','Member\TestController@getResult')->name('get-result');

        Route::get('/huong-dan/{id}','Member\TestController@preview')->name('get-preview');
        
        Route::get('thi/{id}','Member\TestController@detail')->name('test_detail');
        
        Route::post('/submit/{part}','Member\TestController@submit')->name('submit_test');
        
       

    });
});


Route::get('crawl-data', 'Crawl\CrawlController@showView');

Route::get('crawl/data', 'Crawl\CrawlController@showViewV2');


Route::post('run-crawl', 'Crawl\CrawlController@handle')->name('run');



Route::get('/init/test', function (){
    
    $questions = \App\Models\QuestionGroup::all();
    // $questions = \App\Models\QuestionGroup::where('question_group_id','>',45)->get();
    // $photoPath = 'easytoiec/public/storage/photos/shares/test/de1/audio';
    // return response()->json($questions );
    foreach($questions as $item) {
             
        if($item->question_group_image) {
            $item->question_group_image = 'https://toeic24.vn'. $item->question_group_image;
            $item->save();
        }
        // $test = new  App\Models\TestQuestion();
        // $test->test_id = 3;
        // $test->question_group_id =$item->question_group_id;
        // $test->save();
        }
    
    echo "done";

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Providers\AuthServiceProvider;
use App\Models\Role; 
use Illuminate\Database\Eloquent\SoftDeletes; 

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use SoftDeletes;

    public $primaryKey = 'user_id';

    // protected $dateFormat = 'Y-m-d';

    public static function boot()
    {
        parent::boot();
        
        static::creating(function ($model) {
            $userRole = Role::firstWhere('role_name', AuthServiceProvider::USER_ROLE);
            $model->role_id = $userRole->role_id;
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        // 'created_at' => 'date',
    ];


    public function role()
    {
        return $this->hasOne(\App\Models\Role::class, 'role_id', 'role_id');
    }

    public function profile()
    {
        return $this->hasOne(\App\Models\UserProfile::class, 'user_id', 'user_id');
    }

    public function userTests() {

        return $this->hasMany(\App\Models\UserTest::class, 'user_id', 'user_id');
        
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\models\User;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $keyword = $request->keyword;

        $list = User::when( $keyword , function ($query) use ($keyword) {

            $query->join('user_profiles','user_profiles.user_id','=','users.user_id')->where('user_profile_full_name','like','%'.$keyword.'%');
        })->where('user_id','<>',Auth::id())
        ->paginate(10);
        return view('admin.user.list',compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try {
            $ids = explode(',' , $request->ids);
             User::destroy($ids);
             $request->session()->flash('success', "Xoá thành công !");
             return redirect()->route('user.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', "Xoá thất bại !");
            return redirect()->route('user.index');
        }
    }
}

resources/views/admin/user/list.blade.php
@extends('layouts.app_admin')
@section('head')
<title>Quản lý người dùng</title>

@endsection

@section('content')
<div class="d-flex">
    <nav id="breadcrumbs" class="mb-3">
        <ul>
            <li><a href="#"> <i class="uil-home-alt"></i> </a></li>
            <li><a href="#"> Người dùng </a></li>
            <li>Danh sách</li>
        </ul>
    </nav>
</div>




<div class="card">
    <!-- Card header -->
    <div class="card-header actions-toolbar border-0">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="d-inline-block mb-0">Người dùng</h4>
            <div class="d-flex">

                <a href="#" class="btn btn-icon btn-hover  btn-circle" uk-tooltip="Tìm kiếm">
                    <i class="uil-search"></i>
                </a>
                <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                <form method="GET" class="uk-search uk-search-navbar uk-width-1-1" action="{{route('user.index')}}">
                        <input name="keyword" class="uk-search-input shadow-0 uk-form-small" type="text" placeholder="Tìm kiếm"
                            autofocus>
                    </form>
                </div>
                <button id="delete-user" class="btn btn-icon btn-hover  btn-circle " uk-tooltip="Xoá">
                    <i class="uil-trash-alt text-danger"></i>
                    <form method="POST" style="display:node" id="form-delete-user" action="{{ route('user.destroy',0)}}">
                        @method("delete")
                        @csrf
                    </form>
                </button>

            </div>
        </div>
    </div>
    <!-- Table -->
    <div class="table-responsive">
        <table class="table align-items-center">
            <thead>
                <tr>
                    <th>
                        <input class="skin-square all" type="checkbox"  style="display:none">
                    </th>
                    <th scope="col">Tên người dùng</th>
                    <th scope="col">Ngày đăng ký</th>
                    <th scope="col">Số lần thi thử</th>
                    <th scope="col"> </th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($list as $item)
                <tr>
                    <th scope="row">
                        <input style="display:none" value="{{ $item->user_id }}" class="skin-square check" type="checkbox">
                    </th>
                    <th scope="row">
                        <div class="media align-items-center">
                            <div>
                                <div class="avatar-parent-child" style="width: max-content">
                                    <img alt="Image placeholder" src="{{ $item->profile ? asset($item->profile->user_profile_avatar) :   asset('assets/images/no-avt.png') }}"
                                        class="avatar  rounded-circle">

                                </div>
                            </div>
                            <div class="media-body ml-4">
                                <a href="#" class="name h6 mb-0 text-sm">{{ $item->profile ?  $item->profile->user_profile_full_name : ''}}</a>
                                <small class="d-block font-weight-bold">#{{$item->user_id}}</small>
                            </div>
                        </div>
                    </th>
                    <td>{{$item->created_at}}</td>
                    <td class="text-center" >
                    <span class="uk-label uk-label-danger">{{
                        $item->userTests->count()
                        }}</span>
                    </td>

                    <td class="text-right">
                        <!-- Actions -->
                        <div class="actions ml-3">
                            <a href="{{ route('user.show', $item->user_id) }}" class="btn btn-icon btn-hover btn-sm btn-circle" uk-tooltip="Xem chi tiết">
                                <i class="uil-external-link-alt text-info"></i> </a>

                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
        @if($list->isEmpty())
            <div class="text-center">
                Không có bản ghi nào 
            </div>
        @endif
        <div class="text-center" style="float:right;padding: 20px;">
            {{ $list->links('vendor.pagination.default') }}
        </div>
    </div>
</div>

@endsection
@section('js')
<script  src="{{ asset('assets/common/icheck-1.x/icheck.min.js') }}"></script>
<script  src="{{ asset('assets/admin/js/custom-icheck.js') }}"></script>
<script src="{{ asset('assets/admin/js/user/list-user.js') }}"></script>
@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('assets/common/icheck-1.x/skins/all.css') }}">
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app_admin')

@section('head')
    <title>Chi tiết người dùng</title>
@endsection


@section('content')
<h4>Thông tin</h4>

<div uk-grid>

    <div class="uk-width-2-5@m uk-flex-last@m">

        <div class="uk-card-default rounded text-center p-4">
            <div class="uk-position-relative my-4">

                    <div class="user-profile-photo  m-auto">
                    <img src="{{ asset($user->profile->user_profile_avatar) }}" alt="">
                    </div>
            </div>

        </div>
    </div>
    <div class="uk-width-expand@m">

        <div class="uk-card-default rounded">

            <hr class="m-0">
            <form class="uk-child-width-1-2@s uk-grid-small p-4" uk-grid>
                <div>
                    <h5 class="uk-text-bold mb-2"> Họ tên </h5>
                <input  value="{{$user->profile->user_profile_full_name}}" type="text" class="uk-input" readonly>
                </div>
                <div>
                    <h5 class="uk-text-bold mb-2"> Số điện thoại </h5>
                    <input value="{{$user->profile->user_profile_phone}}" type="text" class="uk-input" readonly>
                </div>
                <div>
                    <h5 class="uk-text-bold mb-2"> Email </h5>
                    <input value="{{$user->email}}" type="text" class="uk-input" readonly>
                </div>
                <div>
                    <h5 class="uk-text-bold mb-2"> Địa chỉ </h5>
                    <input value="{{$user->profile->user_profile_address}}" type="text" class="uk-input" readonly>
                </div>
            </form>

            {{-- <div class="uk-flex uk-flex-right p-4">
                <button class="btn btn-default grey">Xoá</button>
            </div> --}}
        </div>
    </div>

</div>
@endsection

@section('css')
    
@endsection

@section('js')
    
@endsection